// Recettes écrites à la main — zéro appel à Gemini pour celles-ci.
// Sert de socle immédiat à la banque de recettes pendant que
// scripts/seedRecipeBank.js (IA) tourne en tâche de fond ou plus tard.
//
// `seasons` : liste des saisons où la recette est pertinente — le script
// d'import crée une ligne recipe_bank par saison listée, pour maximiser les
// chances qu'un profil utilisateur la pioche (voir recipeBank.js > pickFromBank
// qui filtre par diet + season + budget).

export const HANDWRITTEN_RECIPES = [
  {
    label: 'Poêlée de poulet, riz et brocolis',
    searchQuery: 'chicken rice broccoli bowl',
    totalTime: 25, servings: 2, difficulty: 'Facile',
    pricePerServing: 2.4, calories: 520, protein: 42, carbs: 55, fat: 14,
    equipment: ['poêle', 'casserole'],
    ingredientLines: [
      '2 filets de poulet (300 g)', '150 g de riz basmati', '300 g de brocolis',
      '2 gousses d\'ail', '2 c. à soupe d\'huile d\'olive', 'Sel, poivre',
    ],
    steps: [
      'Faire cuire le riz dans une casserole d\'eau bouillante salée pendant 12 minutes, puis égoutter.',
      'Couper le poulet en dés et le faire dorer dans l\'huile d\'olive avec l\'ail émincé pendant 8 minutes.',
      'Cuire les brocolis à la vapeur 6 minutes pour qu\'ils restent croquants.',
      'Assembler le riz, le poulet et les brocolis dans un bol, saler et poivrer avant de servir.',
    ],
    goals: ['muscle'], diet: 'none', seasons: ['printemps', 'été', 'automne', 'hiver'],
  },
  {
    label: 'Curry de pois chiches au lait de coco',
    searchQuery: 'chickpea coconut curry',
    totalTime: 30, servings: 4, difficulty: 'Facile',
    pricePerServing: 1.6, calories: 410, protein: 14, carbs: 48, fat: 18,
    equipment: ['sauteuse'],
    ingredientLines: [
      '2 boîtes de pois chiches (480 g égouttés)', '400 ml de lait de coco', '1 oignon',
      '2 c. à soupe de pâte de curry', '1 boîte de tomates concassées', 'Coriandre fraîche',
    ],
    steps: [
      'Faire revenir l\'oignon émincé dans un peu d\'huile pendant 5 minutes.',
      'Ajouter la pâte de curry et faire cuire 1 minute en remuant pour libérer les arômes.',
      'Verser les tomates concassées, le lait de coco et les pois chiches, laisser mijoter 15 minutes à feu doux.',
      'Servir parsemé de coriandre fraîche, avec du riz ou du pain plat.',
    ],
    goals: ['economy', 'discover'], diet: 'vegan', seasons: ['automne', 'hiver'],
  },
  {
    label: 'Saumon rôti, patates douces et épinards',
    searchQuery: 'roasted salmon sweet potato spinach',
    totalTime: 35, servings: 2, difficulty: 'Moyen',
    pricePerServing: 4.2, calories: 480, protein: 34, carbs: 32, fat: 22,
    equipment: ['four', 'poêle'],
    ingredientLines: [
      '2 pavés de saumon (280 g)', '2 patates douces moyennes', '200 g d\'épinards frais',
      '1 citron', '2 c. à soupe d\'huile d\'olive', 'Sel, poivre',
    ],
    steps: [
      'Préchauffer le four à 200°C. Couper les patates douces en cubes et les enfourner 25 minutes avec un filet d\'huile.',
      'Poser les pavés de saumon sur la même plaque 12 minutes avant la fin de cuisson des patates.',
      'Faire tomber les épinards dans une poêle avec un peu d\'huile pendant 3 minutes.',
      'Dresser le saumon avec les patates douces et les épinards, arroser d\'un filet de citron.',
    ],
    goals: ['weight_loss', 'muscle'], diet: 'pescatarian', seasons: ['automne', 'hiver'],
  },
  {
    label: 'Pâtes aux courgettes et parmesan',
    searchQuery: 'pasta zucchini parmesan',
    totalTime: 20, servings: 2, difficulty: 'Facile',
    pricePerServing: 1.8, calories: 560, protein: 18, carbs: 78, fat: 16,
    equipment: ['casserole', 'poêle'],
    ingredientLines: [
      '200 g de pâtes', '2 courgettes', '1 gousse d\'ail', '40 g de parmesan râpé',
      '2 c. à soupe d\'huile d\'olive', 'Basilic frais',
    ],
    steps: [
      'Faire cuire les pâtes dans un grand volume d\'eau salée selon les indications du paquet.',
      'Couper les courgettes en fines rondelles et les faire dorer dans l\'huile avec l\'ail 8 minutes.',
      'Égoutter les pâtes en gardant un peu d\'eau de cuisson, puis les mélanger aux courgettes.',
      'Ajouter le parmesan et un peu d\'eau de cuisson pour lier, parsemer de basilic frais.',
    ],
    goals: ['economy', 'discover'], diet: 'vegetarian', seasons: ['printemps', 'été'],
  },
  {
    label: 'Buddha bowl quinoa, avocat et pois chiches rôtis',
    searchQuery: 'buddha bowl quinoa avocado chickpeas',
    totalTime: 30, servings: 2, difficulty: 'Facile',
    pricePerServing: 2.9, calories: 490, protein: 16, carbs: 52, fat: 22,
    equipment: ['four', 'casserole'],
    ingredientLines: [
      '150 g de quinoa', '1 boîte de pois chiches', '1 avocat', '1 carotte',
      '2 c. à soupe de tahini', 'Jus de citron', 'Huile d\'olive',
    ],
    steps: [
      'Cuire le quinoa dans deux fois son volume d\'eau pendant 15 minutes, puis égoutter.',
      'Enfourner les pois chiches égouttés avec un filet d\'huile à 200°C pendant 20 minutes.',
      'Préparer une sauce en mélangeant le tahini, le jus de citron et un peu d\'eau.',
      'Dresser le quinoa avec l\'avocat en tranches, la carotte râpée et les pois chiches, arroser de sauce.',
    ],
    goals: ['discover', 'weight_loss'], diet: 'vegan', seasons: ['printemps', 'été'],
  },
  {
    label: 'Omelette aux champignons et fromage',
    searchQuery: 'mushroom cheese omelette',
    totalTime: 15, servings: 1, difficulty: 'Facile',
    pricePerServing: 1.4, calories: 380, protein: 24, carbs: 6, fat: 28,
    equipment: ['poêle'],
    ingredientLines: [
      '3 œufs', '100 g de champignons de Paris', '30 g de fromage râpé',
      '1 c. à soupe de beurre', 'Persil, sel, poivre',
    ],
    steps: [
      'Émincer les champignons et les faire revenir dans le beurre 5 minutes jusqu\'à ce qu\'ils rendent leur eau.',
      'Battre les œufs avec le sel et le poivre.',
      'Verser les œufs sur les champignons, laisser prendre 2 minutes puis parsemer de fromage.',
      'Plier l\'omelette en deux une fois le fromage fondu, parsemer de persil avant de servir.',
    ],
    goals: ['muscle', 'economy'], diet: 'vegetarian', seasons: ['printemps', 'été', 'automne', 'hiver'],
  },
  {
    label: 'Wok de bœuf, poivrons et nouilles',
    searchQuery: 'beef stir fry noodles peppers',
    totalTime: 25, servings: 2, difficulty: 'Moyen',
    pricePerServing: 3.6, calories: 540, protein: 32, carbs: 58, fat: 16,
    equipment: ['wok'],
    ingredientLines: [
      '250 g de bœuf émincé', '200 g de nouilles chinoises', '2 poivrons', '1 oignon',
      '3 c. à soupe de sauce soja', '1 c. à soupe de gingembre frais',
    ],
    steps: [
      'Faire tremper les nouilles selon les indications du paquet, puis égoutter.',
      'Faire saisir le bœuf émincé dans le wok très chaud pendant 3 minutes, réserver.',
      'Faire sauter les poivrons et l\'oignon émincés avec le gingembre pendant 5 minutes.',
      'Remettre le bœuf, ajouter les nouilles et la sauce soja, mélanger 2 minutes sur feu vif avant de servir.',
    ],
    goals: ['muscle', 'discover'], diet: 'none', seasons: ['automne', 'hiver'],
  },
  {
    label: 'Salade de lentilles, feta et légumes rôtis',
    searchQuery: 'lentil feta roasted vegetable salad',
    totalTime: 35, servings: 2, difficulty: 'Facile',
    pricePerServing: 2.2, calories: 420, protein: 18, carbs: 42, fat: 18,
    equipment: ['four', 'casserole'],
    ingredientLines: [
      '150 g de lentilles vertes', '1 courgette', '1 poivron rouge', '80 g de feta',
      '2 c. à soupe d\'huile d\'olive', 'Vinaigre balsamique',
    ],
    steps: [
      'Cuire les lentilles dans l\'eau bouillante non salée pendant 20 minutes, puis égoutter.',
      'Couper la courgette et le poivron en morceaux, les enfourner avec un filet d\'huile à 200°C pendant 20 minutes.',
      'Mélanger les lentilles tièdes avec les légumes rôtis.',
      'Émietter la feta par-dessus, assaisonner d\'huile d\'olive et de vinaigre balsamique.',
    ],
    goals: ['economy', 'weight_loss'], diet: 'vegetarian', seasons: ['été', 'automne'],
  },
  {
    label: 'Cabillaud vapeur, riz et sauce citronnée',
    searchQuery: 'steamed cod rice lemon sauce',
    totalTime: 25, servings: 2, difficulty: 'Facile',
    pricePerServing: 3.8, calories: 400, protein: 36, carbs: 40, fat: 8,
    equipment: ['cuiseur vapeur', 'casserole'],
    ingredientLines: [
      '2 filets de cabillaud (280 g)', '150 g de riz', '1 citron', '1 c. à soupe de crème fraîche légère',
      'Aneth frais', 'Sel, poivre',
    ],
    steps: [
      'Cuire le riz dans une casserole d\'eau bouillante salée pendant 12 minutes.',
      'Cuire les filets de cabillaud à la vapeur pendant 10 minutes.',
      'Préparer une sauce en mélangeant le jus de citron, la crème fraîche et l\'aneth ciselé.',
      'Servir le cabillaud sur le riz, nappé de sauce citronnée.',
    ],
    goals: ['weight_loss'], diet: 'pescatarian', seasons: ['printemps', 'été'],
  },
  {
    label: 'Tofu grillé, riz et brocolis sauce soja-sésame',
    searchQuery: 'grilled tofu rice broccoli sesame',
    totalTime: 25, servings: 2, difficulty: 'Facile',
    pricePerServing: 2.1, calories: 460, protein: 22, carbs: 54, fat: 16,
    equipment: ['poêle', 'casserole'],
    ingredientLines: [
      '250 g de tofu ferme', '150 g de riz', '250 g de brocolis',
      '2 c. à soupe de sauce soja', '1 c. à soupe de graines de sésame', '1 c. à soupe d\'huile de sésame',
    ],
    steps: [
      'Couper le tofu en tranches épaisses et le presser 5 minutes pour retirer l\'excès d\'eau.',
      'Cuire le riz dans une casserole d\'eau bouillante salée pendant 12 minutes.',
      'Faire dorer le tofu dans l\'huile de sésame 3 minutes de chaque côté, puis napper de sauce soja.',
      'Cuire les brocolis à la vapeur 6 minutes, servir le tout avec les graines de sésame par-dessus.',
    ],
    goals: ['muscle', 'discover'], diet: 'vegan', seasons: ['printemps', 'été', 'automne', 'hiver'],
  },
  {
    label: 'Chili sin carne aux haricots rouges',
    searchQuery: 'vegetarian chili beans',
    totalTime: 35, servings: 4, difficulty: 'Facile',
    pricePerServing: 1.5, calories: 380, protein: 16, carbs: 52, fat: 10,
    equipment: ['cocotte'],
    ingredientLines: [
      '2 boîtes de haricots rouges (480 g égouttés)', '1 boîte de maïs', '1 boîte de tomates concassées',
      '1 oignon', '1 poivron', '1 c. à café de cumin', '1 c. à café de paprika fumé',
    ],
    steps: [
      'Faire revenir l\'oignon et le poivron émincés dans un peu d\'huile pendant 6 minutes.',
      'Ajouter le cumin et le paprika, cuire 1 minute pour libérer les arômes.',
      'Verser les tomates concassées, les haricots rouges et le maïs égouttés.',
      'Laisser mijoter à feu doux pendant 20 minutes en remuant de temps en temps.',
    ],
    goals: ['economy', 'discover'], diet: 'vegan', seasons: ['automne', 'hiver'],
  },
  {
    label: 'Poulet rôti au four, légumes racines',
    searchQuery: 'roast chicken root vegetables',
    totalTime: 55, servings: 4, difficulty: 'Moyen',
    pricePerServing: 2.8, calories: 520, protein: 38, carbs: 34, fat: 22,
    equipment: ['four'],
    ingredientLines: [
      '4 hauts de cuisse de poulet', '3 carottes', '2 panais', '4 pommes de terre',
      '2 c. à soupe d\'huile d\'olive', 'Thym, romarin, sel, poivre',
    ],
    steps: [
      'Préchauffer le four à 200°C. Couper les légumes en gros morceaux et les répartir sur une plaque.',
      'Disposer les morceaux de poulet sur les légumes, arroser d\'huile d\'olive et parsemer d\'herbes.',
      'Enfourner 45 minutes en retournant les légumes à mi-cuisson.',
      'Vérifier que le poulet est bien cuit avant de servir avec les légumes rôtis.',
    ],
    goals: ['economy', 'muscle'], diet: 'none', seasons: ['automne', 'hiver'],
  },
  {
    label: 'Taboulé de quinoa, tomates et concombre',
    searchQuery: 'quinoa tabbouleh tomato cucumber',
    totalTime: 20, servings: 2, difficulty: 'Facile',
    pricePerServing: 1.7, calories: 340, protein: 10, carbs: 46, fat: 12,
    equipment: ['casserole'],
    ingredientLines: [
      '150 g de quinoa', '2 tomates', '1/2 concombre', 'Persil frais', 'Menthe fraîche',
      'Jus de citron', '2 c. à soupe d\'huile d\'olive',
    ],
    steps: [
      'Cuire le quinoa dans deux fois son volume d\'eau pendant 15 minutes, laisser refroidir.',
      'Couper les tomates et le concombre en petits dés.',
      'Ciseler le persil et la menthe finement.',
      'Mélanger tous les ingrédients avec le jus de citron et l\'huile d\'olive, réserver au frais 10 minutes avant de servir.',
    ],
    goals: ['weight_loss', 'discover'], diet: 'vegan', seasons: ['printemps', 'été'],
  },
  {
    label: 'Gratin de courge butternut et lentilles corail',
    searchQuery: 'butternut squash red lentil gratin',
    totalTime: 45, servings: 4, difficulty: 'Moyen',
    pricePerServing: 1.9, calories: 400, protein: 14, carbs: 58, fat: 12,
    equipment: ['four', 'casserole'],
    ingredientLines: [
      '1 courge butternut moyenne', '150 g de lentilles corail', '200 ml de lait de coco',
      '1 oignon', '1 c. à café de curcuma', 'Sel, poivre',
    ],
    steps: [
      'Éplucher et couper la courge butternut en cubes, cuire à la vapeur 15 minutes.',
      'Faire revenir l\'oignon émincé, ajouter les lentilles corail, le curcuma et le lait de coco.',
      'Laisser mijoter 15 minutes jusqu\'à ce que les lentilles soient tendres.',
      'Mélanger avec la courge, transférer dans un plat à gratin et enfourner 15 minutes à 200°C.',
    ],
    goals: ['economy', 'discover'], diet: 'vegan', seasons: ['automne', 'hiver'],
  },
  {
    label: 'Sauté de crevettes, courgettes et riz au citron vert',
    searchQuery: 'shrimp zucchini lime rice',
    totalTime: 20, servings: 2, difficulty: 'Facile',
    pricePerServing: 4.5, calories: 420, protein: 30, carbs: 44, fat: 12,
    equipment: ['poêle', 'casserole'],
    ingredientLines: [
      '250 g de crevettes décortiquées', '2 courgettes', '150 g de riz', '1 citron vert',
      '2 gousses d\'ail', '2 c. à soupe d\'huile d\'olive',
    ],
    steps: [
      'Cuire le riz dans une casserole d\'eau bouillante salée pendant 12 minutes, ajouter le zeste de citron vert.',
      'Couper les courgettes en rubans et les faire revenir dans l\'huile avec l\'ail 5 minutes.',
      'Ajouter les crevettes et cuire 3 minutes jusqu\'à ce qu\'elles soient roses.',
      'Servir sur le riz au citron vert, arroser d\'un filet de jus de citron vert.',
    ],
    goals: ['weight_loss', 'muscle'], diet: 'pescatarian', seasons: ['printemps', 'été'],
  },
  {
    label: 'Soupe miso, tofu et champignons',
    searchQuery: 'miso soup tofu mushroom',
    totalTime: 20, servings: 2, difficulty: 'Facile',
    pricePerServing: 1.3, calories: 220, protein: 12, carbs: 18, fat: 10,
    equipment: ['casserole'],
    ingredientLines: [
      '2 c. à soupe de pâte miso', '200 g de tofu soyeux', '100 g de champignons shiitake',
      '2 oignons nouveaux', '750 ml d\'eau ou de bouillon dashi',
    ],
    steps: [
      'Faire chauffer l\'eau ou le bouillon dashi sans le porter à ébullition franche.',
      'Émincer les champignons shiitake et les ajouter au bouillon, cuire 5 minutes.',
      'Délayer la pâte miso dans une louche de bouillon chaud avant de la reverser dans la casserole (elle ne doit jamais bouillir).',
      'Ajouter le tofu coupé en cubes et les oignons nouveaux émincés, servir immédiatement.',
    ],
    goals: ['weight_loss', 'discover'], diet: 'vegan', seasons: ['automne', 'hiver'],
  },
  {
    label: 'Pâtes au thon, tomates cerises et olives',
    searchQuery: 'tuna pasta cherry tomatoes olives',
    totalTime: 20, servings: 2, difficulty: 'Facile',
    pricePerServing: 1.9, calories: 540, protein: 26, carbs: 72, fat: 14,
    equipment: ['casserole', 'poêle'],
    ingredientLines: [
      '200 g de pâtes', '1 boîte de thon au naturel', '200 g de tomates cerises',
      '50 g d\'olives noires', '2 gousses d\'ail', 'Huile d\'olive',
    ],
    steps: [
      'Faire cuire les pâtes dans un grand volume d\'eau salée selon les indications du paquet.',
      'Faire revenir l\'ail émincé dans l\'huile d\'olive, ajouter les tomates cerises coupées en deux 5 minutes.',
      'Ajouter le thon égoutté et les olives, chauffer 2 minutes.',
      'Mélanger avec les pâtes égouttées et servir immédiatement.',
    ],
    goals: ['economy', 'discover'], diet: 'pescatarian', seasons: ['printemps', 'été'],
  },
  {
    label: 'Bol de riz complet, œuf mollet et légumes croquants',
    searchQuery: 'rice bowl soft egg vegetables',
    totalTime: 25, servings: 1, difficulty: 'Facile',
    pricePerServing: 1.8, calories: 460, protein: 18, carbs: 62, fat: 14,
    equipment: ['casserole'],
    ingredientLines: [
      '80 g de riz complet', '1 œuf', '1 carotte', '1/2 avocat',
      '1 c. à soupe de sauce soja', 'Graines de sésame',
    ],
    steps: [
      'Cuire le riz complet dans l\'eau bouillante pendant 25 minutes.',
      'Cuire l\'œuf mollet 6 minutes dans l\'eau bouillante, puis le refroidir sous l\'eau froide et l\'écaler.',
      'Râper la carotte et couper l\'avocat en lamelles.',
      'Dresser le riz avec les légumes et l\'œuf coupé en deux, arroser de sauce soja et parsemer de graines de sésame.',
    ],
    goals: ['weight_loss', 'discover'], diet: 'vegetarian', seasons: ['printemps', 'été', 'automne', 'hiver'],
  },
  {
    label: 'Escalope de dinde, purée de patates douces',
    searchQuery: 'turkey escalope sweet potato mash',
    totalTime: 30, servings: 2, difficulty: 'Facile',
    pricePerServing: 2.6, calories: 460, protein: 36, carbs: 38, fat: 14,
    equipment: ['poêle', 'casserole'],
    ingredientLines: [
      '2 escalopes de dinde (260 g)', '2 patates douces moyennes', '1 c. à soupe de beurre',
      '1 c. à soupe d\'huile d\'olive', 'Thym, sel, poivre',
    ],
    steps: [
      'Éplucher et couper les patates douces en morceaux, cuire à l\'eau bouillante 18 minutes.',
      'Écraser les patates douces avec le beurre pour obtenir une purée.',
      'Faire dorer les escalopes de dinde dans l\'huile 4 minutes de chaque côté avec le thym.',
      'Servir les escalopes accompagnées de la purée de patates douces.',
    ],
    goals: ['muscle', 'weight_loss'], diet: 'none', seasons: ['automne', 'hiver'],
  },
];
